# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db1551972b1250f27f880a3bf00a433636f4eb8635f705f661872934442c07cfdb86467ea8470a730a20a498d5805de427f0b2fae6f019b9ad1a4aa7afe5ec9

test:
  secret_key_base: f02e461347683870a3b4f214187a4c01dd85c49fc43c7b643b8c11b3d65bbfff75652ebeb02af63b2eceb85fd2fe746330ed4c56db3e678bb7093de1bb067ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
